name: Release WoWhisper

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Update TOC to latest interface versions
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: retail
          beta: true
          ptr: true

      - name: Package and Upload to CurseForge
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
