name: Update TOC Interface versions

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Update TOC Interface versions
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: retail
          beta: true
          ptr: true

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          title: Update TOC Interface versions
          commit-message: Update TOC Interface versions to latest
          branch: interface-version
          delete-branch: true
